---
title: JS Output Personalized
toc: true
layout: default
description: A Tech Talk on outputs using HTML and Javascript. This uses jquery for easy onscreen interaction and filtering.
courses: { compsci: {week: 2, categories: [3.A, 5.B]} }
categories: [C3.0, C3.1, C4.1]
type: hacks
---

### Markdown Table
Google [markdown cheat sheet](https://www.markdownguide.org/extended-syntax/#tables) and it will lead you to an outline for how to make a table.

| Make | Model | Year | Color | Price |
|------|-------|------|-------|-------|
|Ford|Mustang|2022|Red|$35,000|
|Toyota|Camry|2022|Silver|$25,00|
|Tesla|Model S|2022|White|$80,000|
|Cadillac|Broughan|1969|Black|$10,000|
|Ford|F-350|1997|Green|$15,000|
|Ford|Excursion|2003|Green|$25,000|
|Ford|Ranger|2012|Red|$8,000|
|Kuboto|L3301 Tractor|2015|Orange|$12,000|
|Ford|Fusion Energi|2015|Green|$15,000|
|Acura|XL|2006|Grey|$10,000|
|Ford|F150 Lightning|2023|Grey|$70,000|

### HTML Table
Google [w3schools html table](https://www.w3schools.com/html/html_tables.asp) and it will lead you to a tutorial on how to make tables.

In [13]:
%%html
<table class="table">
    <thead>
        <tr>
            <th>Make</th>
            <th>Model</th>
            <th>Year</th>
            <th>Color</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Cadillac</td>
            <td>Broughan</td>
            <td>1969</td>
            <td>Black</td>
            <td>$10,000</td>
        </tr>
        <tr>
            <td>Ford</td>
            <td>F-350</td>
            <td>1997</td>
            <td>Green</td>
            <td>$15,000</td>
        </tr>
        <tr>
            <td>Ford</td>
            <td>Excursion</td>
            <td>2003</td>
            <td>Green</td>
            <td>$25,000</td>
        </tr>
        <tr>
            <td>Ford</td>
            <td>Ranger</td>
            <td>2012</td>
            <td>Red</td>
            <td>$8,000</td>
        </tr>
        <tr>
            <td>Kuboto</td>
            <td>L3301 Tractor</td>
            <td>2015</td>
            <td>Orange</td>
            <td>$12,000</td>
        </tr>
        <tr>
            <td>Ford</td>
            <td>Fusion Energi</td>
            <td>2015</td>
            <td>Guard</td>
            <td>$25,000</td>
        </tr>
        <tr>
            <td>Acura</td>
            <td>XL</td>
            <td>2006</td>
            <td>Grey</td>
            <td>$10,000</td>
        </tr>
        <tr>
            <td>Ford</td>
            <td>F150 Lightning</td>
            <td>2024</td>
            <td>Guard</td>
            <td>$70,000</td>
        </tr>
    </tbody>
</table>

### HTML Table with JavaScript jquery
JavaScript is a programming language that works with HTML data, CSS helps to style that data.  In this example, we are using JavaScript and CSS that was developed by others (3rd party).  Addithing the 3rd party code makes the table interactive.
- Look at the href and src on lines inside of the lines in `<head>` tags.  This is adding code to our page from others.
- Observe the `<script>` tags at the bottom of the page.  This is generating the interactive table, from the third party code, using the data `<table id="demo">` from the `<body>`.

In [15]:
%%html

<!-- Head contains information to Support the Document -->
<head>
    <!-- load jQuery and DataTables output style and scripts -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>var define = null;</script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
</head>

<!-- Body contains the contents of the Document -->
<body>
    <table id="demo" class="table">
        <thead>
            <tr>
                <th>Make</th>
                <th>Model</th>
                <th>Year</th>
                <th>Color</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Ford</td>
                <td>Mustang</td>
                <td>2022</td>
                <td>Red</td>
                <td>$35,000</td>
            </tr>
            <tr>
                <td>Toyota</td>
                <td>Camry</td>
                <td>2022</td>
                <td>Silver</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Tesla</td>
                <td>Model S</td>
                <td>2022</td>
                <td>White</td>
                <td>$80,000</td>
            </tr>
            <tr>
                <td>Cadillac</td>
                <td>Broughan</td>
                <td>1969</td>
                <td>Black</td>
                <td>$10,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>F-350</td>
                <td>1997</td>
                <td>Green</td>
                <td>$15,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Excursion</td>
                <td>2003</td>
                <td>Green</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Ranger</td>
                <td>2012</td>
                <td>Red</td>
                <td>$8,000</td>
            </tr>
            <tr>
                <td>Kuboto</td>
                <td>L3301 Tractor</td>
                <td>2015</td>
                <td>Orange</td>
                <td>$12,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Fusion Energi</td>
                <td>2015</td>
                <td>Guard</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Acura</td>
                <td>XL</td>
                <td>2006</td>
                <td>Grey</td>
                <td>$10,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>F150 Lightning</td>
                <td>2024</td>
                <td>Guard</td>
                <td>$70,000</td>
            </tr>
        </tbody>
    </table>
</body>

<!-- Script is used to embed executable code -->
<script>
    $("#demo").DataTable();
</script>

## Hacks
This lesson teaches you about tables.  In this hack, it is important that you analze the difference in the styles of output shown.  
- Make your own tables, with data according to your interests.

<mark><b>This table shows the retail gasoline prices from 2020-2023 ($$/gallon).</b></mark>

<style>
table, th, td {
  border: 3px solid white;
  border-collapse: collapse;
  border-style: dashed;
}
th, td {
  background-color: #96D4D4;
}
</style>

<table>
  <tr>
    <th>Year</th>
    <th>Jan</th>
    <th>Feb</th>
    <th>Mar</th>
    <th>Apr</th>
    <th>May</th>
    <th>Jun</th>
    <th>Jul</th>
    <th>Aug</th>
    <th>Sep</th>
    <th>Oct</th>
    <th>Nov</th>
    <th>Dec</th>
  </tr>
  <tr>
    <td>2020</td>
    <td>2.636</td>
    <td>2.533</td>
    <td>2.329</td>
    <td>1.938</td>
    <td>1.961</td>
    <td>2.170</td>
    <td>2.272</td>
    <td>2.272</td>
    <td>2.274</td>
    <td>2.248</td>
    <td>2.200</td>
    <td>2.284</td>
  </tr>
  <tr>
    <td>2021</td>
    <td>2.420</td>
    <td>2.587</td>
    <td>2.898</td>
    <td>2.948</td>
    <td>3.076</td>
    <td>3.157</td>
    <td>3.231</td>
    <td>3.255</td>
    <td>3.272</td>
    <td>3.384</td>
    <td>3.491</td>
    <td>3.406</td>
  </tr>
  <tr>
    <td>2022</td>
    <td>3.413</td>
    <td>3.611</td>
    <td>4.322</td>
    <td>4.213</td>
    <td>4.545</td>
    <td>5.032</td>
    <td>4.668</td>
    <td>4.087</td>
    <td>3.817</td>
    <td>3.935</td>
    <td>3.799</td>
    <td>3.324</td>
  </tr>
  <tr>
    <td>2023</td>
    <td>3.445</td>
    <td>3.501</td>
    <td>3.535</td>
    <td>3.711</td>
    <td>3.666</td>
    <td>3.684</td>
    <td>3.712</td>
    <td>3.954</td>
  </tr>
</table>

<b>[Source](https://www.eia.gov/dnav/pet/hist/LeafHandler.ashx?n=pet&s=emm_epm0_pte_nus_dpg&f=m) for data.<b>

- <b>Describe a benefit of a markdown table.</b>
  - Markdown tables are easier to type, using only pipes and hyphens with text vs. the complex syntax of HTML tables.
- <b>Try to Style the HTML table using w3schools.</b>
  - Border color, border pattern, border width, background color changed
- <b>Describe the difference between HTML and JavaScript.</b>
  - HTML and Javascript tables are both done in rows, but JavaScript tables can be interactive by using JavaScript and CSS developed by others (3rd party).
- <b>Describe a benefit of a table that uses JavaScript.</b>
  - Tables that use JavaScript can be more interactive, including filtering tabs and sorting through several pieces and categories of data.